packages:
  - apps/*
  - packages/*
  - registry/modules/*
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.22
  vite-plus: ^0.1.22
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.22
ignoredBuiltDependencies:
  - sharp
ignoredOptionalDependencies: []
onlyBuiltDependencies:
  - core-js
  - esbuild
  - msw
  - protobufjs
overrides:
  es-toolkit: 1.47.0
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
