packages:
  - apps/*
  - packages/*
  - registry/modules/*
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.24
  vite-plus: ^0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.24
ignoredOptionalDependencies: []
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  core-js: true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: false
minimumReleaseAgeExclude:
  - "@voidzero-dev/*"
  - "@withstanza/*"
  - vite
  - vite-plus
  - vitest
