packages:
  - apps/*
  - packages/*
  - registry/modules/*

ignoredBuiltDependencies:
  - sharp

ignoredOptionalDependencies: []

onlyBuiltDependencies:
  - core-js
  - esbuild
  - msw
  - protobufjs
