/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SchemaDotjsonRouteImport } from './routes/schema[.]json'
import { Route as OgDotwebpRouteImport } from './routes/og[.]webp'
import { Route as DocsDotmdRouteImport } from './routes/docs[.]md'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryIndexRouteImport } from './routes/registry.index'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs.{$}[.]md'
import { Route as DocsLlmsDottxtRouteImport } from './routes/docs.llms[.]txt'
import { Route as DocsLlmsFullDottxtRouteImport } from './routes/docs.llms-full[.]txt'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as RegistryCategoryIndexRouteImport } from './routes/registry.$category.index'
import { Route as RegistryCategoryIdRouteImport } from './routes/registry.$category.$id'
import { Route as OgDocsChar123Char125DotwebpRouteImport } from './routes/og.docs.{$}[.]webp'
import { Route as ApiSearchModulesRouteImport } from './routes/api.search.modules'
import { Route as ApiSearchDocsRouteImport } from './routes/api.search.docs'
import { Route as OgRegistryCategoryChar123idChar125DotwebpRouteImport } from './routes/og.registry.$category.{$id}[.]webp'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaDotjsonRoute = SchemaDotjsonRouteImport.update({
  id: '/schema.json',
  path: '/schema.json',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotwebpRoute = OgDotwebpRouteImport.update({
  id: '/og.webp',
  path: '/og.webp',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDotmdRoute = DocsDotmdRouteImport.update({
  id: '/docs.md',
  path: '/docs.md',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLlmsDottxtRoute = DocsLlmsDottxtRouteImport.update({
  id: '/docs/llms.txt',
  path: '/docs/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLlmsFullDottxtRoute = DocsLlmsFullDottxtRouteImport.update({
  id: '/docs/llms-full.txt',
  path: '/docs/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryCategoryIndexRoute = RegistryCategoryIndexRouteImport.update({
  id: '/registry/$category/',
  path: '/registry/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryCategoryIdRoute = RegistryCategoryIdRouteImport.update({
  id: '/registry/$category/$id',
  path: '/registry/$category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDocsChar123Char125DotwebpRoute =
  OgDocsChar123Char125DotwebpRouteImport.update({
    id: '/og/docs/{$}.webp',
    path: '/og/docs/{$}.webp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSearchModulesRoute = ApiSearchModulesRouteImport.update({
  id: '/api/search/modules',
  path: '/api/search/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchDocsRoute = ApiSearchDocsRouteImport.update({
  id: '/api/search/docs',
  path: '/api/search/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRegistryCategoryChar123idChar125DotwebpRoute =
  OgRegistryCategoryChar123idChar125DotwebpRouteImport.update({
    id: '/og/registry/$category/{$id}.webp',
    path: '/og/registry/$category/{$id}.webp',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs.md': typeof DocsDotmdRoute
  '/og.webp': typeof OgDotwebpRoute
  '/schema.json': typeof SchemaDotjsonRoute
  '/stats': typeof StatsRoute
  '/api/events': typeof ApiEventsRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms-full.txt': typeof DocsLlmsFullDottxtRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/registry/': typeof RegistryIndexRoute
  '/api/search/docs': typeof ApiSearchDocsRoute
  '/api/search/modules': typeof ApiSearchModulesRoute
  '/og/docs/{$}.webp': typeof OgDocsChar123Char125DotwebpRoute
  '/registry/$category/$id': typeof RegistryCategoryIdRoute
  '/registry/$category/': typeof RegistryCategoryIndexRoute
  '/og/registry/$category/{$id}.webp': typeof OgRegistryCategoryChar123idChar125DotwebpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs.md': typeof DocsDotmdRoute
  '/og.webp': typeof OgDotwebpRoute
  '/schema.json': typeof SchemaDotjsonRoute
  '/stats': typeof StatsRoute
  '/api/events': typeof ApiEventsRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms-full.txt': typeof DocsLlmsFullDottxtRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/registry': typeof RegistryIndexRoute
  '/api/search/docs': typeof ApiSearchDocsRoute
  '/api/search/modules': typeof ApiSearchModulesRoute
  '/og/docs/{$}.webp': typeof OgDocsChar123Char125DotwebpRoute
  '/registry/$category/$id': typeof RegistryCategoryIdRoute
  '/registry/$category': typeof RegistryCategoryIndexRoute
  '/og/registry/$category/{$id}.webp': typeof OgRegistryCategoryChar123idChar125DotwebpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs.md': typeof DocsDotmdRoute
  '/og.webp': typeof OgDotwebpRoute
  '/schema.json': typeof SchemaDotjsonRoute
  '/stats': typeof StatsRoute
  '/api/events': typeof ApiEventsRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms-full.txt': typeof DocsLlmsFullDottxtRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/registry/': typeof RegistryIndexRoute
  '/api/search/docs': typeof ApiSearchDocsRoute
  '/api/search/modules': typeof ApiSearchModulesRoute
  '/og/docs/{$}.webp': typeof OgDocsChar123Char125DotwebpRoute
  '/registry/$category/$id': typeof RegistryCategoryIdRoute
  '/registry/$category/': typeof RegistryCategoryIndexRoute
  '/og/registry/$category/{$id}.webp': typeof OgRegistryCategoryChar123idChar125DotwebpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs.md'
    | '/og.webp'
    | '/schema.json'
    | '/stats'
    | '/api/events'
    | '/docs/$'
    | '/docs/llms-full.txt'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/registry/'
    | '/api/search/docs'
    | '/api/search/modules'
    | '/og/docs/{$}.webp'
    | '/registry/$category/$id'
    | '/registry/$category/'
    | '/og/registry/$category/{$id}.webp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs.md'
    | '/og.webp'
    | '/schema.json'
    | '/stats'
    | '/api/events'
    | '/docs/$'
    | '/docs/llms-full.txt'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/registry'
    | '/api/search/docs'
    | '/api/search/modules'
    | '/og/docs/{$}.webp'
    | '/registry/$category/$id'
    | '/registry/$category'
    | '/og/registry/$category/{$id}.webp'
  id:
    | '__root__'
    | '/'
    | '/docs.md'
    | '/og.webp'
    | '/schema.json'
    | '/stats'
    | '/api/events'
    | '/docs/$'
    | '/docs/llms-full.txt'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/registry/'
    | '/api/search/docs'
    | '/api/search/modules'
    | '/og/docs/{$}.webp'
    | '/registry/$category/$id'
    | '/registry/$category/'
    | '/og/registry/$category/{$id}.webp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsDotmdRoute: typeof DocsDotmdRoute
  OgDotwebpRoute: typeof OgDotwebpRoute
  SchemaDotjsonRoute: typeof SchemaDotjsonRoute
  StatsRoute: typeof StatsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsLlmsFullDottxtRoute: typeof DocsLlmsFullDottxtRoute
  DocsLlmsDottxtRoute: typeof DocsLlmsDottxtRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
  ApiSearchDocsRoute: typeof ApiSearchDocsRoute
  ApiSearchModulesRoute: typeof ApiSearchModulesRoute
  OgDocsChar123Char125DotwebpRoute: typeof OgDocsChar123Char125DotwebpRoute
  RegistryCategoryIdRoute: typeof RegistryCategoryIdRoute
  RegistryCategoryIndexRoute: typeof RegistryCategoryIndexRoute
  OgRegistryCategoryChar123idChar125DotwebpRoute: typeof OgRegistryCategoryChar123idChar125DotwebpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema.json': {
      id: '/schema.json'
      path: '/schema.json'
      fullPath: '/schema.json'
      preLoaderRoute: typeof SchemaDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.webp': {
      id: '/og.webp'
      path: '/og.webp'
      fullPath: '/og.webp'
      preLoaderRoute: typeof OgDotwebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs.md': {
      id: '/docs.md'
      path: '/docs.md'
      fullPath: '/docs.md'
      preLoaderRoute: typeof DocsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/': {
      id: '/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/llms.txt': {
      id: '/docs/llms.txt'
      path: '/docs/llms.txt'
      fullPath: '/docs/llms.txt'
      preLoaderRoute: typeof DocsLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/llms-full.txt': {
      id: '/docs/llms-full.txt'
      path: '/docs/llms-full.txt'
      fullPath: '/docs/llms-full.txt'
      preLoaderRoute: typeof DocsLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$category/': {
      id: '/registry/$category/'
      path: '/registry/$category'
      fullPath: '/registry/$category/'
      preLoaderRoute: typeof RegistryCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$category/$id': {
      id: '/registry/$category/$id'
      path: '/registry/$category/$id'
      fullPath: '/registry/$category/$id'
      preLoaderRoute: typeof RegistryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/docs/{$}.webp': {
      id: '/og/docs/{$}.webp'
      path: '/og/docs/{$}.webp'
      fullPath: '/og/docs/{$}.webp'
      preLoaderRoute: typeof OgDocsChar123Char125DotwebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/modules': {
      id: '/api/search/modules'
      path: '/api/search/modules'
      fullPath: '/api/search/modules'
      preLoaderRoute: typeof ApiSearchModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/docs': {
      id: '/api/search/docs'
      path: '/api/search/docs'
      fullPath: '/api/search/docs'
      preLoaderRoute: typeof ApiSearchDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/registry/$category/{$id}.webp': {
      id: '/og/registry/$category/{$id}.webp'
      path: '/og/registry/$category/{$id}.webp'
      fullPath: '/og/registry/$category/{$id}.webp'
      preLoaderRoute: typeof OgRegistryCategoryChar123idChar125DotwebpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsDotmdRoute: DocsDotmdRoute,
  OgDotwebpRoute: OgDotwebpRoute,
  SchemaDotjsonRoute: SchemaDotjsonRoute,
  StatsRoute: StatsRoute,
  ApiEventsRoute: ApiEventsRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsLlmsFullDottxtRoute: DocsLlmsFullDottxtRoute,
  DocsLlmsDottxtRoute: DocsLlmsDottxtRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
  RegistryIndexRoute: RegistryIndexRoute,
  ApiSearchDocsRoute: ApiSearchDocsRoute,
  ApiSearchModulesRoute: ApiSearchModulesRoute,
  OgDocsChar123Char125DotwebpRoute: OgDocsChar123Char125DotwebpRoute,
  RegistryCategoryIdRoute: RegistryCategoryIdRoute,
  RegistryCategoryIndexRoute: RegistryCategoryIndexRoute,
  OgRegistryCategoryChar123idChar125DotwebpRoute:
    OgRegistryCategoryChar123idChar125DotwebpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
