/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OgIndexRouteImport } from './routes/og.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as OgSlotIdRouteImport } from './routes/og.$slot.$id'
import { Route as MSlotIdRouteImport } from './routes/m.$slot.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgIndexRoute = OgIndexRouteImport.update({
  id: '/og/',
  path: '/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSlotIdRoute = OgSlotIdRouteImport.update({
  id: '/og/$slot/$id',
  path: '/og/$slot/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlotIdRoute = MSlotIdRouteImport.update({
  id: '/m/$slot/$id',
  path: '/m/$slot/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/events': typeof ApiEventsRoute
  '/docs/$': typeof DocsSplatRoute
  '/og/': typeof OgIndexRoute
  '/m/$slot/$id': typeof MSlotIdRoute
  '/og/$slot/$id': typeof OgSlotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/events': typeof ApiEventsRoute
  '/docs/$': typeof DocsSplatRoute
  '/og': typeof OgIndexRoute
  '/m/$slot/$id': typeof MSlotIdRoute
  '/og/$slot/$id': typeof OgSlotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/events': typeof ApiEventsRoute
  '/docs/$': typeof DocsSplatRoute
  '/og/': typeof OgIndexRoute
  '/m/$slot/$id': typeof MSlotIdRoute
  '/og/$slot/$id': typeof OgSlotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/events'
    | '/docs/$'
    | '/og/'
    | '/m/$slot/$id'
    | '/og/$slot/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/events'
    | '/docs/$'
    | '/og'
    | '/m/$slot/$id'
    | '/og/$slot/$id'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/events'
    | '/docs/$'
    | '/og/'
    | '/m/$slot/$id'
    | '/og/$slot/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiEventsRoute: typeof ApiEventsRoute
  DocsSplatRoute: typeof DocsSplatRoute
  OgIndexRoute: typeof OgIndexRoute
  MSlotIdRoute: typeof MSlotIdRoute
  OgSlotIdRoute: typeof OgSlotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/': {
      id: '/og/'
      path: '/og'
      fullPath: '/og/'
      preLoaderRoute: typeof OgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$slot/$id': {
      id: '/og/$slot/$id'
      path: '/og/$slot/$id'
      fullPath: '/og/$slot/$id'
      preLoaderRoute: typeof OgSlotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slot/$id': {
      id: '/m/$slot/$id'
      path: '/m/$slot/$id'
      fullPath: '/m/$slot/$id'
      preLoaderRoute: typeof MSlotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiEventsRoute: ApiEventsRoute,
  DocsSplatRoute: DocsSplatRoute,
  OgIndexRoute: OgIndexRoute,
  MSlotIdRoute: MSlotIdRoute,
  OgSlotIdRoute: OgSlotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
