import { createFileRoute } from "@tanstack/react-router";
import { llms } from "fumadocs-core/source";

import { source } from "@/lib/source";

/**
 * `/llms.txt` — a Markdown index of every docs page, following the
 * https://llmstxt.org convention. Generated by Fumadocs' `llms()` helper.
 */
export const Route = createFileRoute("/llms.txt")({
  server: {
    handlers: {
      GET: () =>
        new Response(llms(source).index(), {
          headers: {
            "content-type": "text/plain; charset=utf-8",
            "cache-control": "public, max-age=3600, s-maxage=86400",
          },
        }),
    },
  },
});
