import type { ReactNode } from "react";

import "./globals.css";

export const metadata = {
  title: "Stanza app",
  description: "Generated by Stanza",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
